#!/bin/bash

docker run \
  --name mender-client-docker-launcher \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e MAC_ADDRESS="$(cat /sys/class/net/eth0/address)" \
  -e MENDER_PAT \
  -e DEVICE_TYPE=virtual \
  mender-client-docker-launcher
