#!/bin/bash

docker run \
  --rm \
  --name mender-client-docker-launcher \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e TENANT_TOKEN \
  -e DEVICE_TYPE=virtual \
  mender-client-docker-launcher
