#!/bin/bash

args=(
  --device-type "$DEVICE_TYPE"
  --inventory-poll 600
  --quiet
  --retry-poll 5
  --tenant-token "$TENANT_TOKEN"
  --demo-server=false
  --server-cert ""
  --update-poll 5
)

if [ -n "$MENDER_HOST" ]; then
  args+=(--server-url "$MENDER_HOST")
fi

mender-setup "${args[@]}"
