name: Push workflow
on:
  push:
    branches:
      - main
    tags:
  pull_request:
jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      -
        # TODO remove?
        name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          version: 27.3.1
      - name: GHCR Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker Buildx builder setup
        uses: docker/setup-buildx-action@v3.11.1
        with:
          version: v0.19.1
      -
        id: docker-bake
        name: Docker Bake
        uses: docker/bake-action@v5.7.0
        with:
          workdir: .
          source: https://github.com/rcwbr/dockerfile-partials.git#0.10.0
          files: github-cache-bake.hcl, cwd://docker-bake.hcl
        env:
          REGISTRY: ghcr.io/rcwbr/
          IMAGE_NAME: mender-client-docker
    outputs:
      docker-bake: ${{ steps.docker-bake.outputs.metadata }}
  devcontainer-cache-build:
    uses: rcwbr/devcontainer-cache-build/.github/workflows/devcontainer-cache-build.yaml@0.6.0
    permissions:
      packages: write
  release-it-workflow:
    uses: rcwbr/release-it-gh-workflow/.github/workflows/release-it-workflow.yaml@0.2.4
    with:
      app-id: 1632440 # mender-client-docker release-it app
      app-environment: Repo release
      # Use the file bumper release-it image
      release-it-image: ghcr.io/rcwbr/release-it-docker-file-bumper:0.7.0
    secrets:
      app-secret: ${{ secrets.RELEASE_IT_GITHUB_APP_KEY }} # Secret belonging to the Repo release environment
  pre-commit:
    if: github.event_name == 'pull_request'
    uses: rcwbr/dockerfile-partials/.github/workflows/pre-commit.yaml@0.4.0
    needs: devcontainer-cache-build
    with:
      pre-commit-image: ${{ fromJSON(needs.devcontainer-cache-build.outputs.devcontainer-cache-image-all_configs).target.pre-commit.args.DEVCONTAINER_PRE_COMMIT_IMAGE }}
